---
- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Install packages on Ubuntu for OpenStack base Services
    apt:
      name:
        - vim
        - htop
        - curl
        - wget
      state: present
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - neutron
    - horizon
    - cinder

